Re-added check for upstart, updated php5-fpm-checkconfig
- php5-fpm-checkconfig now uses exit value of php5-fpm
- fpm init script is back to using php5-fpm-checkconfig

diff --git a/debian/php5-fpm-checkconf b/debian/php5-fpm-checkconf
--- a/debian/php5-fpm-checkconf
+++ b/debian/php5-fpm-checkconf
@@ -1,9 +1,8 @@
 #!/bin/sh
-set -e
-errors=$(/usr/sbin/php5-fpm --fpm-config /etc/php5/fpm/php-fpm.conf -t 2>&1 | grep "\[ERROR\]" || true);
-if [ -n "$errors" ]; then
+[ "$1" != "no" ] && /usr/sbin/php5-fpm --fpm-config /etc/php5/fpm/php-fpm.conf -t 2>&1 | grep -wv "ERROR"
+if ! errors=$(/usr/sbin/php5-fpm --fpm-config /etc/php5/fpm/php-fpm.conf -t 2>&1); then
     echo "Please fix your configuration file..."
-    echo $errors
+    printf "%s\n" "$errors" | grep ERROR
     exit 1
 fi
 exit 0
